#!/bin/bash

declare para=$1

translate()
{  
	result=`curl -s \
	"http://fanyi.youdao.com/translate?smartresult=dict& \
	smartresult=rule&smartresult=ugc&sessionFrom=dict.top" \
	-d \
	"type=AUTO&i=${para}&doctype=json&xmlVersion=1.4& \
	keyfrom=fanyi.web&ue=UTF-8&typoResult=true&flag=false"`
	#result=`uname -a`
	
	echo $result | sed -r -n 's/.*tgt":"([^"]+)".*/\1/p' 
	echo "---------------------------------------------"
	echo $result 
		    
	return 0;								    
}

translate;
